spring:
  application:
    name: auction-server
  datasource:
    url: jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  websocket:
    buffer-size: 256KB

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: false